swagger:
  doc:
    resources:
      log-api:
        name: log-api
        api-docs-path: /v2/api-docs
        server-url: http://localhost:10010
      admin-api:
        name: admin-api
        api-docs-path: /v2/api-docs
        server-url: http://localhost:10020
      auth-api:
        name: auth-api
        api-docs-path: /v2/api-docs
        server-url: http://localhost:10030